### ISSUE TITLE
Traefik Basic Auth for all services not working

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#101]
**Describe the bug**
After choosing basic authentification for all traefik services, containers are unable to find traefik.htpasswd file.
With every container there is error:
open /path/to/base_dir/traefik/traefik.passwd: no such file or directory

Path is unacesible from other containers

**To Reproduce**
During setup choose basic authentification for all services

**Expected behavior**
Working authentification.
REason of not working is, that containers are looking for path from inside of container.

Solution:
mount same volume to every traefik container:
    - ${BASE_DIR}/traefik/traefik.passwd:/traefik.passwd

 and use only /traefik.passwd path in auth section.

**Comment by joskore** [comment]
i fixed this earlier and apparently it didn't get committed. -_-

we don't even need to mount the file in the containers, the fact that it's mounted in the traefik is all we need as traefik uses its filesystem for locating the file, not the client container's

tested and merged in #102
