### ISSUE TITLE
Wrong path for Portainer config

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#105]
**Describe the bug**
In the newest version Portainer path has 2 // 

${CONTAINER_DIR}/portainer//config:/data

**To Reproduce**
Selection Portainer
Checking yaml. after creation

**Expected behavior**
Slash should be only once

**Comment by joskore** [comment]
paths can have multiple consecutive slashes, it doesn't adversely affect anything. i've gone ahead and changed it just to make it look nice, though. thanks!
