### ISSUE TITLE
Cannot connect to localhost

### ISSUE THREAD

**Issue by imerkle** [joskore/media-docker#113]
When adding deluge in radarr it says `Unable to connect` or adding radarr in jackett it does not connect either

**Comment by Antexa** [comment]
Could you be more specific ? 

Can you provide the connection details you type in the form ?

**Comment by cthog** [comment]
Not to necro, but I have this issue--localhost in Sonarr or Radarr settings doesn't work, so I have to type in the ip address.

**Comment by joskore** [comment]
no worries! you should be able to communicate with each container by the container name itself. “localhost” is dependent on the container you’re in (at least i’m *pretty* sure that’s how docker’s internal DNS functions), whereas you can instead access each service by its name as its hostname. 

for instance, sonarr is accessible as “sonarr”, plex at “plex”, and radarr is accessible as “radarr”

think of each service as an independent host within a network with its own internal IP and hostname and you should be good to go. hopefully this helps!
