### ISSUE TITLE
Cannot install ombi with emby

### ISSUE THREAD

**Issue by DotDotSpaceDotDot** [joskore/media-docker#116]
**Describe the bug**
When installing ombi with emby error message is displayed.
ERROR: Service 'ombi' depends on service 'plex' which is undefined.

**To Reproduce**
1. SSH into server
2. run sudo media-docker
3. Select emby and ombi for installation
4. start installation
5. See error

**Expected behavior**
ombi can be installed with emby.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu server 18.04LTS

**Additional context**

**Comment by joskore** [comment]
this is fair, i’ll remove that dependency shortly

**Comment by joskore** [comment]
i've removed this dependency for the ombi container, it now will start regardless of plex being enabled.
