### ISSUE TITLE
Use the plex claim system for docker

### ISSUE THREAD

**Issue by mattheys** [joskore/media-docker#2]
Instead of having to tunnel into Plex why not use the claim system they have for docker and put that in the .env file.

**Comment by joshuhn** [comment]
is there a meaningful improvement to doing so? from a cursory review, it's exchanging one manual process for another, and using the claims system adds a time constraint to the process while also requiring a change to the image we're using for the plex container.

if folks feel strongly about this being a better solution, we can move that way, i'm just not seeing it off-hand. what am i missing?

**Comment by mattheys** [comment]
It was more a feature request rather than issue. Personally I think it would be easier to go to https://plex.tv/claim and copy and paste that into a text file. The benefit is for remote headless systems where you have to create an SSH tunnel in order to connect to Plex and login. Also I didn't realise that it wasn't supported by this Plex docker image. Maybe keep it in mind if/when Linuxserver.io support the claim method.

**Comment by joskore** [comment]
migration to the plexinc official image and implementation of the claim token system has been made in PR #10

thanks!
