### ISSUE TITLE
compose_install.sh improvement

### ISSUE THREAD

**Issue by csreynolds** [joskore/media-docker#23]
**Describe the bug**
Extra space in script malforms variable on ubuntu18 fresh minimal install.

**To Reproduce**
1. creynolds@reynolds-ubuntu-18:/media-docker$ sudo ./media-docker.sh --prereq
[INFO] [2018-11-13T18:49:46+0000]  Starting manual app configuration process.
[INFO] [2018-11-13T18:49:47+0000]  Starting prerequistes install.
[INFO] [2018-11-13T18:49:50+0000]  Updating apt repositories.
[INFO] [2018-11-13T18:49:56+0000]  Cleaning up remnants of unused packages.
[SUCCESS]  [2018-11-13T18:49:58+0000]  Successfully installed requested packages.
[INFO] [2018-11-13T18:50:08+0000]  Updating apt repositories.
[INFO] [2018-11-13T18:50:13+0000]  Cleaning up remnants of unused packages.
[SUCCESS]  [2018-11-13T18:50:16+0000]  Successfully installed requested packages.
/media-docker/.scripts//compose_install.sh: line 9: 1.23.0-rc3/docker-compose-Linux-x86_64: No such file or directory
[INFO] [2018-11-13T18:50:16+0000]  Installing Docker Compose.
/media-docker/.scripts//compose_install.sh: line 13: URL: unbound variable
Failed to start docker.service: Unit docker.service not found.

**Expected behavior**
Installs prereqs.

**Additional context**
Remove single space in .scripts/compose_install.sh line 9 before \ fixes problem.

**Comment by joskore** [comment]
oof! splitting strings across lines is the bane of my existence and i hate how it always does these things to us.

updated the script and resolved, thanks for finding this and pointing it out.
