### ISSUE TITLE
error occurred creating Docker network

### ISSUE THREAD

**Issue by 1DontEx1st** [joskore/media-docker#31]
**Describe the bug**
During guided setup, after entering the Plex claim token, hitting Ok kicks out to an error

**To Reproduce**
1. Virgin Ubuntu machine
2. Run through guided setup
3. Error happens after entering Plex claim token

**Screenshots**
![Screenshot](https://i.imgur.com/A1g10ke.png)

possibly related to whatever is causing #30

**Comment by joskore** [comment]
hey, thanks for letting me know! would you be able to share the earlier points in the log? clearly docker is failing to install, but i'm not sure why it's letting you past that point if it fails.

**Comment by joskore** [comment]
i was able to replicate this on a fresh machine and have made some updates to the pre-requisite install process in #33 

my testing shows this issue resolved, let me know if your issues continue

**Comment by joskore** [comment]
copying this in from the pull request comment:

> 
> 
> I re-imaged my server and re-fetched from git and now the guided installer (and sudo media-docker -p) is failing with "Error cleaning legacy packages." - looks like the script is dependent on zypper, which isn't installed.

so there have been some changes made to the system to allow for other package managers, but its detection is based on distro-specific files existing. you shouldn't be seeing a requirement for zypper unless you're running SuSE of some sort.

what's the output of `uname -a` on your machine?

**Comment by joskore** [comment]
alrighty, @1DontEx1st, i was able to replicate a form of this issue again after a re-image, and i believe (🤞) that we've gotten everything fixed up.

you certainly don't need to re-image again, but if you could do the following for me i would greatly appreciate it:

1. delete the directory you cloned media-docker into
2. re-clone media-docker `git clone https://github.com/joskore/media-docker ./media-docker && cd ./media-docker`
3. `chmod +x media-docker.sh`
4. `sudo media-docker.sh`
5. run through the guided installer as normal, or run the above with the `-p` option.

i've added some additional checks surrounding package management, dependencies, etc. that should resolve all of the issues you've noted. if you continue to have these problems, definitely let me know and we'll figure them out together. a lot has changed in this project recently, but hopefully this'll all be solid from here on out

**Comment by 1DontEx1st** [comment]
That worked! Now it's time to play around with containers. Thanks!
