### ISSUE TITLE
Let's Encrypt Dns Resolve Option

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#49]
DNS Resolve option for Encrypt is missing due to hardcoded TOML file

**Proposed Solution:**
Slight modification of *.toml file, based on menu choice between https or dns resolve

If DNS resolve choosen, menu to select Provider and set variables in .env file

**TOML** file part for DNS Resolve with Cloudflare provider:
[acme.dnsChallenge]
  provider = "cloudflare"

**.env** values to setup
DNS_EMAIL_ADDRESS=
DNS_API_KEY=

**Traefik.yaml** (in case of Cloudflare)
    environment:
    - CLOUDFLARE_EMAIL=${DNS_EMAIL_ADDRESS}
    - CLOUDFLARE_API_KEY=${DNS_API_KEY}

**Comment by joskore** [comment]
resolved in #60, you're now given options for dns or http challenge and can select a variety of dns providers
