### ISSUE TITLE
Traefik Dashboard Secure Access

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#50]
**Is your feature request related to a problem? Please describe.**
Dashboard is accesible by anyone from internet. It should be possible to password-protect it

**Describe the solution you'd like**
Install additional linux package for htpasswd. Then create Traefik password for defined user into file - Traefik.passwd

Add this file to volumes in Trafik.yaml:
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ${BASE_DIR}/traefik/traefik.toml:/traefik.toml
    - ${BASE_DIR}/traefik/acme.json:/acme.json
    - ${BASE_DIR}/traefik/traefik.passwd:/traefik.passwd

Modify TOML section with TRafik entry point like that:
address = ":8080"
    [entryPoints.traefik.auth.basic]
    usersfile = "/traefik.passwd"

Now the dashboard is password protected

**Comment by joskore** [comment]
implemented this in #59. thanks for pointing it out!
