### ISSUE TITLE
Customization of media sub-folder's names

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#63]
**Is your feature request related to a problem? Please describe.**
TV, Movies, Music, Books, Comics names are hardcoded right now. Sometimes media structure is already set (on shared folders, NAS devices, etc.) so it cannot be recreated with current hardcoded values

**Describe the solution you'd like**
Customizable name for media subfolders via .env variables.
Add to .env
MEDIA_DIR_MOVIES=Movies/
MEDIA_DIR_MUSIC=Music/
MEDIA_DIR_TV=TV/
MEDIA_DIR_BOOKS=Books/
MEDIA_DIR_COMICS=Comics/

Then in containers configurations it can be used like that:
${MEDIA_DIR}/${MEDIA_DIR_MOVIES}:/movies

It will solve also cases where Comics are child folders to Books - in .env user can configure it like that:
MEDIA_DIR_COMICS=Books/Comics/

**Describe alternatives you've considered**
Use yaml creation and then manually alter compose file

**Comment by joskore** [comment]
added in #72
