### ISSUE TITLE
Wrong folder configuration in Beets

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#64]
**Describe the bug**
internal container path is set to /movies

**To Reproduce**
Its default value in beets.yaml file

**Expected behavior**
folder should be set to /music

      - ${MEDIA_DIR}/Music:/music

**Desktop (please complete the following information):**
 - OS: Ubuntu in VM machine on Synology

**Additional context**

**Comment by joskore** [comment]
oof, you caught me on my laziness there. updated
