### ISSUE TITLE
Wrong donwload folder mapping on host for Jackett and Hydra

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#65]
**Describe the bug**
Folder mapping on host leads to BASE_DIR although it should be DOWNLOAD_DIR

**To Reproduce**
In standard jackett.yaml and nzbhydra.yaml

**Expected behavior**
Blackhole folders are located in DOWNLOAD_DIR

**Screenshots**

**Desktop (please complete the following information):**
 - OS: VM on Synology

**Comment by joskore** [comment]
i generally considered these as separate from the downloads, but do get how grouping them together could be beneficial. updated to put these same directory structures in the download directory going forward
