### ISSUE TITLE
portainer not using ${BASE_DIR}

### ISSUE THREAD

**Issue by powerdude** [joskore/media-docker#68]
**Describe the bug**
Portainer is configured as ` - /config/portainer:/data`

**To Reproduce**
look at portainer.yaml

**Expected behavior**
Portainer should be configured as ` - ${BASE_DIR}/portainer:/data`

**Screenshots**
n/a

**Desktop (please complete the following information):**
latest

**Additional context**
none

**Comment by joskore** [comment]
good catch, that was a holdover from my original config outside of media-docker. updated in most recent commit.
