### ISSUE TITLE
Oscarr configured with host config directory of 'morpheus65535'

### ISSUE THREAD

**Issue by powerdude** [joskore/media-docker#69]
**Describe the bug**
for consistency, the host config directory should be named like the others instead of `- ${BASE_DIR}/morpheus65535/config:/oscarr/data`

**To Reproduce**
look in oscarr.yaml

**Expected behavior**
the volume should be mapped like: `- ${BASE_DIR}/oscarr/config:/oscarr/data`

**Screenshots**
n/a

**Desktop (please complete the following information):**
all

**Additional context**
none

**Comment by joskore** [comment]
while this isn't inherently a problem, i do understand why it could be confusing. updated this volume reference.
