### ISSUE TITLE
Guided Installation cannot proceed

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#70]
**Describe the bug**
When going through Guided installation, there is Timezone menu and then Basic Folder Config menu. There its possible to configure all folders but setup cannot continue because there is no option to go further.
Exit option will exit whole process, OK button will go into selected folder config

**To Reproduce**
run guided setupt
Setup Timezone,
Setup folders and try to continue

**Expected behavior**
There should be option to continue.
Or Exit button should not mean exit all process but exit only current menu and continue.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: VM Ubuntu on Synology

**Comment by khostri** [comment]
Additional info - its not just guided instalation, but also manual one. I was unable to find exact reason, but it seems to me, that if you click exit, result depends on starting status of environment values:
1) if there were already filled values in .env and other files, next menu is opened and installation continues.
2) if there were no values and those values are provided for the first time in current menu, clicking exit exits whole process - no new menu is opened.

**Comment by joskore** [comment]
i agree that this is frustrating, but in the end this is mostly a limitation of whiptail (the program used for these menus). we could probably figure out some way to communicate parent menus back and forth to children, allowing us to move appropriately, but it doesn't seem worth it when this functionality is literally just running down the list of the manual config process.

i'm removing the guided config. going forward, we'll just need to run through the manual configuration process.

**Comment by joskore** [comment]
re: to the additional info, because you beat me to the punch

this was two separate problems. the above regarding the guided process still stands, but the issue with the unset env variables was separate. i've identified the issue in our method for extracting those values, and have gotten it fixed in the current version.
