### ISSUE TITLE
Docker-Compose Timeout

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#71]
**Describe the bug**
with many application selected the time for docker-compose to finish is too short and timeout occurs (60 second)

**To Reproduce**
Select many applications
Start docker containers via menu or docker-compose

**Expected behavior**
There should be enough time to finish deployment.
Solution is to setup COMPOSE_HTTP_TIMEOUT to higher value in .env file.
for example COMPOSE_HTTP_TIMEOUT=180

**Desktop (please complete the following information):**
 - OS: VM Ubuntu on Synology

**Comment by joskore** [comment]
added this in #72

**Comment by khostri** [comment]
Variable name should be COMPOSE_HTTP_TIMEOUT

In current .env file, variable name is COMPOSE_TIMEOUT so it doesnt work
