### ISSUE TITLE
add traefik basic auth to all services

### ISSUE THREAD

**Issue by powerdude** [joskore/media-docker#73]
**Is your feature request related to a problem? Please describe.**
Like what was done to for the traefik dashboard screen, can basic auth be added to all services if the user wants it.

**Describe the solution you'd like**
Would like to have this label:
`- "traefik.frontend.auth.basic=${HTPASSWD}"`
added to all configs if the user desires it.

**Describe alternatives you've considered**
Configuring security separately for each service if the service allows for it

**Additional context**
none

**Comment by joskore** [comment]
in #74 i've added a question to the traefik configuration process. if you indicate that you'd like to use traefik basic auth for all services, it will make use of the traefik.passwd file set up for traefik auth. rather than using the label combo you noted above, i went with
```yaml
  labels:
    - traefik.frontend.auth.basic.usersFile=${BASE_DIR}/traefik/traefik.passwd
```
