### ISSUE TITLE
MariaDB

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#91]
**Please describe the benefits of the application over others already provided, if any apply.**
Database backend for Kodi Centralised Deployment. All Kodi clients are able to share one DB, updated automatically by Kodi headless

**Project URL**
https://hub.docker.com/r/linuxserver/mariadb/

**Comment by joskore** [comment]
this has been implemented as a connected service to kodi-headless. i went with the library image of mariadb rather than the linuxserver.io one.
