### ISSUE TITLE
Little more verbose output during docker-compose

### ISSUE THREAD

**Issue by khostri** [joskore/media-docker#94]
**Is your feature request related to a problem? Please describe.**
Right now when anything fails, there is only one message without any detail. So every time docker-compose has to be started again manually to see what is wrong

**Describe the solution you'd like**
It would be great to at least see steps for container creation. At least on the level of container names and result - like with standard docker compose. It is not necessary to have detailed verbose output, but at least some additional info

**Comment by joskore** [comment]
agreed, i've allowed docker-compose's output to show in the terminal as well as be tee'd into the logfile going forward
